### PR TITLE
add myself as maintainer [ci skip]

### PR DESCRIPTION
**Pull request by carlodri**

### CODE REVIEW

**Comment by vamega** [comment]
Hi @carlodri , I notice that you're trying to add yourself as a maintainer to a large number of packages in the conda-forge ecosystem. Is there a reason you want to maintain this particular package?

**Comment by carlodri** [comment]
@vamega I'm patiently trying to hijack the entire conda-forge ecosystem 😈😜...

jokes apart, main reasons are:
1. I like contributing to such a great and invaluable resource for the community as conda-forge
2. I want to try this package for a project I'm working on
3. the package is out of date and recipe needs some love ❤️

That said, if you're not ok with me being a maintainer, no problem, I'll open appropriate PRs to update things!

**Comment by vamega** [comment]
Sounds good, just recent events in a different package ecosystem had me questioning things.

**Comment by carlodri** [comment]
no problem, I'm happy to decide things together to maintain the recipe in the optimal way!

**Pull request merged**
